### ISSUE TITLE
Schematic Submission 

### ISSUE THREAD

**Issue by timChase98** [umd-jfl/ECE388Project#2]
- [ ] Add me an an admin to the repo
- [ ] Review the submission guidelines [HERE](https://github.com/timChase98/388Example)
- [ ] All project files should be version controlled
- [ ] Schematic should be on one page with an US LETTER frame 

Please address these issues and push your changes. Then create a new release, increment the tag and close this issue. I will review the changes and mark this as complete or reopen the issue with additional feedback.

**Comment by timChase98** [comment]
How do test signals come on to the board? You also still need to add me as and admin to the repo

**Comment by umd-jfl** [comment]
The signal will be send to the A pins of SN74543 chip.
________________________________

**Comment by timChase98** [comment]
How to they get onto the board from the outside world?

**Comment by umd-jfl** [comment]
I was thinking use the pins that was use for the breakout boards. I don't really know the name for it.
________________________________

**Comment by umd-jfl** [comment]
I was thinking that I can make vias and connect the vias to those pins. Will that work? And I can go and order the pins myself. In the schematic, I adjust it and indicate that the inputs will got to these pin.
________________________________

**Comment by timChase98** [comment]
Just add a pin header for these signals

**Comment by timChase98** [comment]
Schematic is accepted.  Moving on to layout

**Comment by umd-jfl** [comment]
I push the pcb into the github already. When you have a chance can you check that off too. Thank you
________________________________
