### ISSUE TITLE
Board Submission

### ISSUE THREAD

**Issue by timChase98** [umd-jfl/ECE388Project#3]
- [ ] Review the submission guidelines [HERE](https://github.com/timChase98/388Example)
- [ ] All project files should be version controlled
- [ ] Boards will not be graded unless both Eagle files and correctly generated Gerber files are present
- [ ] All traces should hit the center of pads
- [ ] Power traces should have a minimum width of 12 mil or run through a plane
- [ ] Silkscreen labels must include
  - [ ] Your Name
  - [ ] Project Name
  - [ ] Date
  - [ ] Version/Rev
  - [ ] Github Link
- [ ] Your project would fit on a much smaller board
- [ ] Placement of fiducials should be 
  - [x] FID1 lower left 
  - [x] FID2 upper left
  - [x] FID3 lower right
- [x] You should label the pinout of your connectors on the silk screen 

These are initial comments meant to guide you though the layout process.  I will not look at your board again until your schematic passes review.  This is to reduce the workload on you by limiting the number of times you need to relayout your board due to schematic errors.  

Please address these issues and push your changes. Then create a new release, increment the tag and close this issue. I will review the changes and mark this as complete or reopen the issue with additional feedback.

**Comment by timChase98** [comment]
Max board size is 100mm x 100mm

**Comment by timChase98** [comment]
Your board outline doesn't match your layout.  Edit the Dimensions layer to match your board

**Comment by umd-jfl** [comment]
If the max board size is 100mm square, I don't know how I can make my PCB, the pin connector that I used is 9.42mm by 71.02mm which is over 100 mm square by itself. And I will fix the board outline right now.
________________________________

**Comment by timChase98** [comment]
100 mm x 100mm not 100 mm^2

**Comment by umd-jfl** [comment]
when I measure the entire board, it shows that the board is 84.02 mm by 91.01mm. The number are mirrored because when I measure it, I'm at bPlace.
________________________________

**Comment by timChase98** [comment]
When I look at your gerber files you outline layer is larger than your board.  The black background is the board outline

**Comment by umd-jfl** [comment]
Can you check to see if I most recent files are satisfied?  I'm not quite sure how to used the GerbV software especially when during lab, our TA never told us about it before.
________________________________

**Comment by timChase98** [comment]
I'll fix it.  Your board will be sent to fab.

**Comment by umd-jfl** [comment]
Okay, thank you so much

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
